/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootSpaRouteImport } from './routes/__root.spa'
import { Route as PutawayRouteImport } from './routes/putaway'
import { Route as PicklistRouteImport } from './routes/picklist'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderNewRouteImport } from './routes/order-new'
import { Route as IndexRouteImport } from './routes/index'

const _rootSpaRoute = _rootSpaRouteImport.update({
  id: '/__root/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const PutawayRoute = PutawayRouteImport.update({
  id: '/putaway',
  path: '/putaway',
  getParentRoute: () => rootRouteImport,
} as any)
const PicklistRoute = PicklistRouteImport.update({
  id: '/picklist',
  path: '/picklist',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNewRoute = OrderNewRouteImport.update({
  id: '/order-new',
  path: '/order-new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/order-new': typeof OrderNewRoute
  '/orders': typeof OrdersRoute
  '/picklist': typeof PicklistRoute
  '/putaway': typeof PutawayRoute
  '/spa': typeof _rootSpaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order-new': typeof OrderNewRoute
  '/orders': typeof OrdersRoute
  '/picklist': typeof PicklistRoute
  '/putaway': typeof PutawayRoute
  '/spa': typeof _rootSpaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/order-new': typeof OrderNewRoute
  '/orders': typeof OrdersRoute
  '/picklist': typeof PicklistRoute
  '/putaway': typeof PutawayRoute
  '/__root/spa': typeof _rootSpaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/order-new' | '/orders' | '/picklist' | '/putaway' | '/spa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/order-new' | '/orders' | '/picklist' | '/putaway' | '/spa'
  id:
    | '__root__'
    | '/'
    | '/order-new'
    | '/orders'
    | '/picklist'
    | '/putaway'
    | '/__root/spa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderNewRoute: typeof OrderNewRoute
  OrdersRoute: typeof OrdersRoute
  PicklistRoute: typeof PicklistRoute
  PutawayRoute: typeof PutawayRoute
  _rootSpaRoute: typeof _rootSpaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/spa': {
      id: '/__root/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof _rootSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putaway': {
      id: '/putaway'
      path: '/putaway'
      fullPath: '/putaway'
      preLoaderRoute: typeof PutawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picklist': {
      id: '/picklist'
      path: '/picklist'
      fullPath: '/picklist'
      preLoaderRoute: typeof PicklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-new': {
      id: '/order-new'
      path: '/order-new'
      fullPath: '/order-new'
      preLoaderRoute: typeof OrderNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderNewRoute: OrderNewRoute,
  OrdersRoute: OrdersRoute,
  PicklistRoute: PicklistRoute,
  PutawayRoute: PutawayRoute,
  _rootSpaRoute: _rootSpaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
