/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TroubleshootRouteImport } from './routes/troubleshoot'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PutawayRouteImport } from './routes/putaway'
import { Route as PicklistRouteImport } from './routes/picklist'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderNewRouteImport } from './routes/order-new'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const TroubleshootRoute = TroubleshootRouteImport.update({
  id: '/troubleshoot',
  path: '/troubleshoot',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PutawayRoute = PutawayRouteImport.update({
  id: '/putaway',
  path: '/putaway',
  getParentRoute: () => rootRouteImport,
} as any)
const PicklistRoute = PicklistRouteImport.update({
  id: '/picklist',
  path: '/picklist',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNewRoute = OrderNewRouteImport.update({
  id: '/order-new',
  path: '/order-new',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/order-new': typeof OrderNewRoute
  '/orders': typeof OrdersRoute
  '/picklist': typeof PicklistRoute
  '/putaway': typeof PutawayRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/troubleshoot': typeof TroubleshootRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/order-new': typeof OrderNewRoute
  '/orders': typeof OrdersRoute
  '/picklist': typeof PicklistRoute
  '/putaway': typeof PutawayRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/troubleshoot': typeof TroubleshootRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/order-new': typeof OrderNewRoute
  '/orders': typeof OrdersRoute
  '/picklist': typeof PicklistRoute
  '/putaway': typeof PutawayRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/troubleshoot': typeof TroubleshootRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/maintenance'
    | '/order-new'
    | '/orders'
    | '/picklist'
    | '/putaway'
    | '/search'
    | '/settings'
    | '/troubleshoot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/maintenance'
    | '/order-new'
    | '/orders'
    | '/picklist'
    | '/putaway'
    | '/search'
    | '/settings'
    | '/troubleshoot'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/maintenance'
    | '/order-new'
    | '/orders'
    | '/picklist'
    | '/putaway'
    | '/search'
    | '/settings'
    | '/troubleshoot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OrderNewRoute: typeof OrderNewRoute
  OrdersRoute: typeof OrdersRoute
  PicklistRoute: typeof PicklistRoute
  PutawayRoute: typeof PutawayRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TroubleshootRoute: typeof TroubleshootRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troubleshoot': {
      id: '/troubleshoot'
      path: '/troubleshoot'
      fullPath: '/troubleshoot'
      preLoaderRoute: typeof TroubleshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putaway': {
      id: '/putaway'
      path: '/putaway'
      fullPath: '/putaway'
      preLoaderRoute: typeof PutawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picklist': {
      id: '/picklist'
      path: '/picklist'
      fullPath: '/picklist'
      preLoaderRoute: typeof PicklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-new': {
      id: '/order-new'
      path: '/order-new'
      fullPath: '/order-new'
      preLoaderRoute: typeof OrderNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OrderNewRoute: OrderNewRoute,
  OrdersRoute: OrdersRoute,
  PicklistRoute: PicklistRoute,
  PutawayRoute: PutawayRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TroubleshootRoute: TroubleshootRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
